### ISSUE TITLE
Не работает поиск идентификатора инфоблока по его коду в init.php

### ISSUE THREAD

**Issue by dmitrichev** [marvin255/bxfoundation#1]
Добрый день!
При использовании компонента в init.php не возвращает null вместо идентификатора инфоблока.
```php
use Bitrix\Main\Loader;
use marvin255\bxfoundation\application\Application;

Loader::includeModule('marvin255.bxfoundation');

Application::getInstance()->locator->get('iblocklocator')->getIdByCode('quests')
```
В других местах работает, но в init.php - нет.
В чем может быть проблема?

**Comment by marvin255** [comment]
К сожалению, не знал про то, что ["SITE_ID - Идентификатор текущего сайта при использовании в Публичной части, код языка при использовании в административной части"](https://dev.1c-bitrix.ru/api_help/main/general/constants.php).
