### ISSUE TITLE
хардкодинг при сборке массива?

### ISSUE THREAD

**Issue by fortobe** [marvin255/bxfoundation#2]
Штука отличная, очень выручает, но почему в bxfoundation:includes/class.php массив собирается в ограниченном виде? по сути, он просто дублирует некоторые поля из выборки с ключами, приведёнными к нижнему регистру, что может быть произведено более динамично. 
Столкнулся с задачей, где мне нужно было добавить пару свойств к инфоблоку, и я немного переписал алгоритм сборки результирующего массива:

while ($el = $res->getNextElement()) {
            $ob = [];
            $fields = $el->GetFields();
            $props = $el->GetProperties();
            foreach ($fields as $field => &$value) {
                if ($field === 'PREVIEW_PICTURE') {
                    $value = $value
                        ? CFile::getFileArray($value)
                        : null;
                }
                if ($field === 'DETAIL_PICTURE') {
                    $value = $value
                        ? CFile::getFileArray($value)
                        : null;
                }
                $ob[strtolower($field)] = $value;
            }
            if (!empty($props)) {
                foreach ($props as $prop => &$val) {
                    if ($val['PROPERTY_TYPE'] === 'F') {
                        $val['VALUE'] = CFile::GetFileArray($val['VALUE']);
                    }
                    if (isset($val['VALUE']['TEXT'])) {
                        $val['VALUE'] = $val['VALUE']['TEXT'];
                    }
                    if (!isset($ob[strtolower($prop)])) {
                        $ob[strtolower($prop)] = $val['VALUE'];
                    } else {
                        $ob['prop_'.strtolower($prop)] = $val['VALUE'];
                    }
                }
            }
            $return[$fields['CODE']] = $ob;
        }

Но, при следующем обновлении композером, мои правки покатились к чертям) Можно ли рассмотреть мой вариант решения этой задачи или аналогичный? Может, конечно, я чего-то не понимаю, но хочу понять. Благодарю заранее

**Comment by marvin255** [comment]
Компонент был написан скорее для работы внутри нашей компании. В общем-то почти в ста процентах случаев его хватает. 

Я вижу два варианта:
